
services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    volumes:
      - ./gateway/certs:/app/certs  # Corrigido caminho
    depends_on:
      - auth
    networks:
      - backend

  auth:
    build: ./services/auth
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql+asyncpg://auth_user:auth_pass@auth_db/auth_db
    depends_on:
      - auth_db
    volumes:
      - ./services/auth/certs:/app/certs  # Corrigido caminho
    networks:
      - backend

  auth_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/certs:/app/certs  # Corrigido caminho
    networks:
      - backend
      - frontend

volumes:
  auth_db_data:

networks:
  backend:
  frontend:
