version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth
      - users
      - ml

  auth:
    build: ./services/auth
    ports:
      - "8001:8001"

  users:
    build: ./services/users
    ports:
      - "8002:8002"

  ml:
    build: ./services/ml
    ports:
      - "8003:8003"

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  postgres_data:
  grafana_data:
